"""
Django settings for django_pycnikr project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')(+jzex&xyweje3&ux1m5lxd2p+$%a8^!f5#94s7t^8k5bl!)('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pycnikr',
    'tilestache',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'django_pycnikr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_pycnikr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Zoom used when displaying the map
PYCNIKR_DEFAULT_ZOOM = 5

# Coordinates of the center of the map when displaying the map
PYCNIKR_DEFAULT_CENTER_LAT = 48.8534100
PYCNIKR_DEFAULT_CENTER_LON = 2.3488000

# The key is the style sheet name used in the URL
# - The first element of the value is the source file of the Python style sheet
# - The second element of the value is the destination file of the XML style sheet
#   Caution: only the file is created, not the intermediate directories
# - The third element is interpreted as following:
#   - If it [], the style sheet is a base layer
#   - It is not [], the style sheet is an overlay, and the user can select the
#     base layer in the list, the first one being selected by default
PYCNIKR_STYLE_SHEETS_MAPPING = \
    {'example':
         (os.path.join(BASE_DIR, 'pycnikr', 'style_sheets', 'example.py'),
          '/tmp/example.xml',
          [],
          ),
     'example2':
         (os.path.join(BASE_DIR, 'pycnikr', 'style_sheets', 'example2.py'),
          '/tmp/example2.xml',
          [],
          ),
     }

# If PYCNIKR_TILE_SERVER_URL = {'left': 'left/',
#                               'center': '/center/',
#                               'right': '.png',
#                               }
# the URL of the tile {z}/{x}/{y} for the style sheet 'name' is
# 'left/name/center/{z}/{x}/{y}.png
PYCNIKR_TILE_SERVER_URL = {'left': 'http://127.0.0.1:8081/',
                           'center': '/',
                           'right': '.png',
                           }

# This callback is called when the user previews the map
# This is the place to indicate to the tile server to refresh its style sheets
PYCNIKR_PREVIEW_CALLBACK = lambda : None
